### ISSUE TITLE
version` is obsolete  &timeout

### ISSUE THREAD

**Issue by firstylemen** [QingHeYang/EasyAccounts#1]
'

**Comment by QingHeYang** [comment]
If you are using Docker image mirrors in China, I'm sorry to inform you that around June, many Docker mirror sites were blocked in mainland China. This has made it impossible to pull images, resulting in timeouts. I am currently looking for alternative solutions. Most likely, I will package the images into tar files and make them available for download from some online storage services. Thank you for your support!

And I`m using Docker Compose version 1.29.2.  you can change version number by yourself

**Comment by QingHeYang** [comment]
我增加了阿里云的镜像库，具体部署参阅：  
https://github.com/QingHeYang/EasyAccounts/blob/main/README-Deploy.md#启动项目
