### ISSUE TITLE
HTTP ERROR 502 &ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by firstylemen** [QingHeYang/EasyAccounts#3]
谢谢，上一个问题已经解决，现在遇到如下问题
我用的是git +vscode+WindTerm
在VScode中目录，已经修改了ip
![Pasted image 20240711101450](https://github.com/QingHeYang/EasyAccounts/assets/96809240/a6aaeec5-ea5f-41ee-a5ca-bc4953c1ef4a)

***

***
打开VPN的情况下会提示“HTTP ERROR 502
***

**Comment by QingHeYang** [comment]
我在自己的阿里云ECS中进行过测试，是可以部署通过的，如果你使用阿里云的ECS云服务器，建议你检查服务器的防火墙以及对应EndPoint的安全组设置
![image](https://github.com/QingHeYang/EasyAccounts/assets/19968251/6002e9f0-392a-45c2-99c7-89c9348b7542)
![image](https://github.com/QingHeYang/EasyAccounts/assets/19968251/e205c6d1-bb1b-4fbf-8c28-d821633e8096)
![image](https://github.com/QingHeYang/EasyAccounts/assets/19968251/03d515fa-f98a-4b64-a91f-fdab958f9973)

如果你没有改变默认端口的情况下，添加 10669-10670端口

不过不建议使用云服务器，这个系统没有auth认证等功能，暂时没有安全性更新的计划

**Comment by firstylemen** [comment]
谢谢，这个问题也解决了。建议做个auth认证功能，因为在外面有事也需要记账
![image](https://github.com/QingHeYang/EasyAccounts/assets/96809240/01ee6792-39dc-499a-8775-6f28d80b9788)
