### ISSUE TITLE
webhook已经按提示配置，Nginx可以看到备份的sql和excel，但是QQ邮箱无法收到邮件，是哪里出了问题，谢谢

### ISSUE THREAD

**Issue by firstylemen** [QingHeYang/EasyAccounts#4]
webhook已经按提示配置，Nginx可以看到备份的sql和excel，但是邮箱无法收到邮件，是哪里出了问题，谢谢。
备份的时间是北京时间晚上22点，为什么这里显示的是14:00

![image](https://github.com/user-attachments/assets/75ac9af2-5e09-4643-8cd8-952a5ba6340c)
![image](https://github.com/user-attachments/assets/a39dac12-10a9-447d-b17c-fe748ba73ccc)

**Comment by QingHeYang** [comment]
WebHook日志目录地址为 `WebHook/hook.log`，你可以查看一下具体问题，刚刚我在新环境中测试了下，发现QQ邮箱可以接到消息：
![image](https://github.com/user-attachments/assets/99e6b57f-d9b9-460c-8491-22a3d7462b6b)

你可能遇到的问题是密码错误的问题，QQ邮箱的smtp授权码并不是他的账号密码，具体参考[QQ邮箱设置](https://service.mail.qq.com/detail/0/75)  

另修复了月度账单以外账单无法发送邮箱的问题，你可以将这几行加入到`WebHook/webhook-email.py`中：
https://github.com/QingHeYang/EasyAccounts/blob/9a51900b55d68b491d1dca32ad1d23234c523bd0/WebHook/webhook-email.py#L53-L61

**Comment by firstylemen** [comment]
![image](https://github.com/user-attachments/assets/1b3147ca-2b8c-431a-a4b2-bb29d95bd07e)
QQ邮箱smtp 授权码已经按提示设置，还是会有这个问题

Hotmail配置也是提示错误
![image](https://github.com/user-attachments/assets/ee7811d3-ff26-45e7-8155-7efb8855a55a)

**Comment by QingHeYang** [comment]
看了下报错，qq邮箱的授权码应该是16位，建议检查密码前后空格问题

**Comment by firstylemen** [comment]
是的，授权码改成16位，可以收到邮件了。各种账单和数据库都可以接收。非常感谢。保存数据库和excel功能真的非常有用。之前我用的记账软件广告时间越来越长了，而且我也用的是苹果。
![image](https://github.com/user-attachments/assets/a58701f2-a903-4ac6-9ce1-d50a4fa0c86e)

**Comment by QingHeYang** [comment]
好的，帮到你就好
