### ISSUE TITLE
[Feature Request]: 飞牛nas docker老是报错，是否可以写个教程

### ISSUE THREAD

**Issue by firstylemen** [QingHeYang/EasyAccounts#9]
在飞牛系统中用docker compese安装后会反复重启，是否可以出个安装教程，谢谢

**Comment by QingHeYang** [comment]
可以，容我回家找个虚拟机安装一下飞牛OS，如果没猜错，八成是文件访问权限的问题，你的cpu与内存配置怎么样

**Comment by QingHeYang** [comment]
暂时没空录制视频，我查了下，确实是文件访问权限的问题，具体的部署步骤如下：
1. 上传项目：
<img width="891" alt="{0F5275ED-1D02-45EC-A4B3-F5AD18F5F1FD}" src="https://github.com/user-attachments/assets/02bbfe05-94b7-4876-8fdf-89c1758b2e47">  

2. 登录飞牛OS后端  
<img width="355" alt="{001351F3-A452-4FD5-B4C2-C5A9D55D2A33}" src="https://github.com/user-attachments/assets/00729da9-b827-4f4e-a9d3-5d03a844844e">  

3. 执行命令找到项目，如果你能找到存放的位置，继续下一步即可
```
sudo find / -type d -name "Easy-Accounts" 2>/dev/null #注意文件夹名称可能不是Easy-Accounts
```  

4. 进入文件夹  并提权，如果你已经有了历史数据库脚本请放置在init文件夹下  ，没有的话，请使用`./Database/base_sql`目录下的基础文件夹    
执行提权：  
```
sudo chown -R 999:999 ./Database/init
```  

5. 这时用户权限应该如下：  
<img width="311" alt="{213B7A85-1EE3-4646-9236-227C8344D8F1}" src="https://github.com/user-attachments/assets/037c5b5f-1ff8-4d3e-bb42-05e6ff7312d0">  

6. 回到浏览器面板继续配置  
<img width="684" alt="{4BCD5F90-7818-4985-B30D-2318184DBF1B}" src="https://github.com/user-attachments/assets/9353cd59-41b5-4b1a-bc26-36f9a299e08a">  

按照部署文档要求配置即可，如果你已经有了compose文件，修改一下IP即可  

7. 构建  
<img width="573" alt="{51C25944-A952-4DD2-8A88-49F59E7A6445}" src="https://github.com/user-attachments/assets/8dfad8d6-57fd-459a-a401-9b859c783e7c">  

<img width="534" alt="{529052B2-E4C2-4A67-B476-726F6C908CB7}" src="https://github.com/user-attachments/assets/8067b9c0-a9ba-4b80-9755-a0116449c888">

**Comment by firstylemen** [comment]
![image](https://github.com/user-attachments/assets/9512be77-e51a-43fa-ab6d-3bfbb3f6babf)

**Comment by firstylemen** [comment]
![9e19e95d723f6d4bbe6798bf670c1a2](https://github.com/user-attachments/assets/c31a9abc-0289-438e-9b89-6142ef85df02)
提权这部不成功

**Comment by QingHeYang** [comment]
我还真没遇到这个情况
1. 按照教程继续操作一下，看是否能够正常启动项目
2. 然后看一下easy_accounts_db的日志，是否有Permission denied，没有表示启动成功
3. 如果有的话，删除 ./Database/data文件夹
4. 查询docker-chromium用户组id:
```
id docker-chromium
```
输出可能如下：
![image](https://github.com/user-attachments/assets/1e4d077e-5d34-4863-896a-1e778fbfb52d)

然后重新执行：  
```
sudo chown -R {查到的uid}:999 ./Database/init  
```

5. 重新构建并尝试  

PS:魔改的debain的nas权限做的都挺垃圾的，我研究半天，人都麻了  


最后  
如果还不行，你就在控制台按照ubuntu的方法部署就行了，这个肯定能成功

**Comment by firstylemen** [comment]
![image](https://github.com/user-attachments/assets/6d0cbc44-92b2-41d5-a709-b9c5b4f834e6)
日志中没有Permission denied，网页可以打开
![image](https://github.com/user-attachments/assets/2cbf5494-4f03-4199-b25b-ef4d56079f9b)
但是无法创建收支，账户。添加无效

**Comment by QingHeYang** [comment]
命令应该是，不带大括号：  
sudo chown -R 990:999 ./Database/init 

然后记得删除掉 ./Database/data文件夹，这个比较重要，因为要是没读取到数据库脚本，mysql会自动初始化一个空的数据库出来，你没发写入数据可能就是这个原因

sudo rm -rf ./Database/data

**Comment by firstylemen** [comment]
![image](https://github.com/user-attachments/assets/16c54d19-ac40-4dce-a0ef-9190e5e7c8db)
![image](https://github.com/user-attachments/assets/8db9f0cc-0e1d-4113-adcd-c6e265abe387)
现在提取权限对了，但是日志中Permission denied

**Comment by firstylemen** [comment]
将文件放在root 目录下运
![image](https://github.com/user-attachments/assets/b5ebc29b-eaaa-4a09-a78d-b255b283e3f8)
![image](https://github.com/user-attachments/assets/0d1762fd-b867-4ff1-bd36-7ed647c364fc)
![image](https://github.com/user-attachments/assets/dfb48eaa-e951-4bcc-8291-c214b1878093)
看似都正常，但是还是无法添加账户，创建收支。该怎么设置权限？

**Comment by QingHeYang** [comment]
要是两个日子都正常的话，老哥你是不是没修改compose里的ip地址啊，所以前端连不上后台，照理说你这个情况实在不应该啊

**Comment by firstylemen** [comment]
忘记改compose中的IP了，已经解决。谢谢
